services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: insurance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    configs:
      - source: postgres_init
        target: /docker-entrypoint-initdb.d/init.sql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - insurance-network

  # RabbitMQ Message Queue
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - insurance-network

  # Backend API
  backend-api:
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USERNAME:-insurance}/insurance-backend:${IMAGE_TAG:-latest}
    environment:
      DB_HOST: database
      DB_NAME: insurance_db
      DB_USER: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_QUEUE: policy_generation
    secrets:
      - postgres_password
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - insurance-network

  # Frontend
  frontend:
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USERNAME:-insurance}/insurance-frontend:${IMAGE_TAG:-latest}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - insurance-network

  # Nginx Proxy
  nginx-proxy:
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USERNAME:-insurance}/insurance-nginx:${IMAGE_TAG:-latest}
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - insurance-network

networks:
  insurance-network:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

secrets:
  postgres_password:
    external: true

configs:
  postgres_init:
    external: true
  nginx_config:
    external: true

